# **********************************
# * Parameters for metqc pipeline *
# **********************************

# List of files
list_files: "/home/aschick/projects/hmptest/list_files.txt"

# Path to sequences
path: "/home/aschick/projects/hmptest/data/rawdata/"

# Choose whether to run cutadapt
include_megahit: FALSE

# Params for metaspades

# Params for metaquast
