# **********************************
# * Parameters for metqc pipeline *
# **********************************

# List of files
list_files: "/home/aschick/projects/hmptest/list_files.txt"

# Path to sequences
path: "/home/aschick/projects/hmptest/data/rawdata/"

# Params for metaspades
error_corr: TRUE

# Params for metaquast
