# ***************************************
# * Parameters for metassemble pipeline *
# ***************************************

# List of files
list_files: "/home/aschick/projects/hmptest/list_files.txt"

# Path to sequences
path: "/home/aschick/projects/hmptest/data/rawdata/"

# Parameters for metaspades
error_corr: TRUE

# Params for metaquast
